"""reporter/pdf_reporter.py — PDF report generator using ReportLab."""
from __future__ import annotations

import datetime
import io

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from typing import Any

from core.interfaces import Reporter
from core.models import Severity, ScanResult

_SEV_COLORS = {
    Severity.CRITICAL: colors.HexColor("#d32f2f"),
    Severity.HIGH:     colors.HexColor("#f57c00"),
    Severity.MEDIUM:   colors.HexColor("#fbc02d"),
    Severity.LOW:      colors.HexColor("#388e3c"),
    Severity.INFO:     colors.HexColor("#1976d2"),
    Severity.PASS:     colors.HexColor("#757575"),
}

_SEV_ORDER = [
    Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM,
    Severity.LOW, Severity.INFO, Severity.PASS,
]


class PDFReporter(Reporter):
    """
    PDF structure:
    1. Cover page          — title, target, date, legal disclaimer
    2. Executive Summary   — risk score, severity counts table
    3. Scope & Methodology — what was done / what was not done
    4. Findings by Severity
    5. Appendix            — scan metadata
    """

    def render(self, result: ScanResult) -> bytes:
        buf  = io.BytesIO()
        doc  = SimpleDocTemplate(
            buf, pagesize=A4,
            rightMargin=2 * cm, leftMargin=2 * cm,
            topMargin=2 * cm, bottomMargin=2 * cm,
        )
        styles = getSampleStyleSheet()
        story: list = []

        story += self._cover(result, styles)
        story.append(PageBreak())
        story += self._exec_summary(result, styles)
        story.append(PageBreak())
        story += self._scope(result, styles)
        story.append(PageBreak())
        story += self._findings(result, styles)
        story.append(PageBreak())
        story += self._appendix(result, styles)

        doc.build(story)
        return buf.getvalue()

    # ── Section builders ──────────────────────────────────────────────────

    def _cover(self, result: ScanResult, styles) -> list[Any]:
        elems: list[Any] = [Spacer(1, 4 * cm)]
        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Title"],
            fontSize=22,
            spaceAfter=14,
            textColor=colors.HexColor("#1a237e"),
        )
        elems.append(Paragraph("WebScan — Defensive Vulnerability Report", title_style))
        elems.append(Spacer(1, 0.5 * cm))

        info_style = ParagraphStyle("Info", parent=styles["Normal"], fontSize=11, spaceAfter=6)
        elems.append(Paragraph(f"<b>Target:</b> {result.target_url}", info_style))
        elems.append(Paragraph(f"<b>Scan type:</b> {result.scan_type.value}", info_style))
        elems.append(Paragraph(f"<b>Scan ID:</b> {result.scan_id}", info_style))
        finished = result.finished_at or datetime.datetime.utcnow()
        elems.append(Paragraph(f"<b>Report date:</b> {finished.strftime('%Y-%m-%d %H:%M UTC')}", info_style))
        elems.append(Paragraph(f"<b>Risk score:</b> {result.risk_score} / 100", info_style))

        elems.append(Spacer(1, 1 * cm))
        disclaimer_style = ParagraphStyle(
            "Disclaimer",
            parent=styles["Normal"],
            fontSize=9,
            textColor=colors.red,
            borderColor=colors.red,
            borderWidth=1,
            borderPadding=6,
        )
        elems.append(Paragraph(
            "<b>LEGAL DISCLAIMER:</b> This report was generated by an authorised user who "
            "owns the target or holds explicit written permission to test it. "
            "Unauthorised scanning is illegal under the CFAA, Computer Misuse Act, and "
            "equivalent laws. No exploit payloads were used during this scan.",
            disclaimer_style,
        ))
        return elems

    def _exec_summary(self, result: ScanResult, styles) -> list[Any]:
        elems: list[Any] = [Paragraph("Executive Summary", styles["Heading1"])]
        by_sev = result.by_severity
        data = [["Severity", "Count", "Highest CWE"]] + [
            [
                s.value.capitalize(),
                str(len(by_sev[s])),
                ", ".join({f.cwe for f in by_sev[s] if f.cwe}),
            ]
            for s in _SEV_ORDER
            if s != Severity.PASS
        ]
        tbl = Table(data, hAlign="LEFT", colWidths=[4 * cm, 2 * cm, 9 * cm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), colors.HexColor("#1a237e")),
            ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID",          (0, 0), (-1, -1), 0.5, colors.black),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
        ]))
        elems.append(tbl)
        elems.append(Spacer(1, 0.5 * cm))

        summary_text = result.metadata.get("executive_summary") or (
            f"Scan of {result.target_url} yielded {len(result.findings)} total findings "
            f"with an overall risk score of {result.risk_score}/100. "
            f"Critical findings: {len(by_sev[Severity.CRITICAL])}. "
            f"High findings: {len(by_sev[Severity.HIGH])}."
        )
        elems.append(Paragraph(summary_text, styles["Normal"]))
        return elems

    def _scope(self, result: ScanResult, styles) -> list[Any]:
        elems: list[Any] = [Paragraph("Scope & Methodology", styles["Heading1"])]
        elems.append(Paragraph(f"<b>Target URL:</b> {result.target_url}", styles["Normal"]))
        elems.append(Paragraph(f"<b>Scan type:</b> {result.scan_type.value}", styles["Normal"]))
        elems.append(Spacer(1, 0.3 * cm))
        elems.append(Paragraph(
            "All checks used HEAD or GET HTTP methods only. POST requests were only issued "
            "if the user provided an explicit safe test prompt for AI endpoint probes. "
            "No exploit payloads, credential stuffing, brute force, or active injection "
            "of any kind was performed. Concurrent requests were capped at 3 with a "
            "0.5-second inter-request politeness delay.",
            styles["Normal"],
        ))
        elems.append(Spacer(1, 0.3 * cm))
        checks_done = sorted({f.check_id.split(".")[0] for f in result.findings})
        elems.append(Paragraph(
            f"<b>Check categories performed:</b> {', '.join(checks_done) or 'none'}",
            styles["Normal"],
        ))
        return elems

    def _findings(self, result: ScanResult, styles) -> list[Any]:
        elems: list[Any] = [Paragraph("Findings", styles["Heading1"])]
        by_sev = result.by_severity
        for sev in _SEV_ORDER:
            group = by_sev[sev]
            if not group:
                continue
            elems.append(Paragraph(
                f"{sev.value.upper()} ({len(group)})",
                ParagraphStyle(
                    f"SevHead_{sev.value}",
                    parent=styles["Heading2"],
                    textColor=_SEV_COLORS[sev],
                ),
            ))
            for finding in group:
                elems += self._finding_block(finding, sev, styles)
        return elems

    def _finding_block(self, finding, sev: Severity, styles) -> list[Any]:
        colour = _SEV_COLORS[sev]
        elems: list[Any] = []
        elems.append(HRFlowable(width="100%", thickness=1, color=colour))

        badge_style = ParagraphStyle(
            f"badge_{sev.value}_{finding.id[:8]}",
            parent=styles["Normal"],
            textColor=colors.white,
            backColor=colour,
            borderPadding=4,
            fontSize=9,
        )
        elems.append(Paragraph(f"[{sev.value.upper()}]  {finding.title}", badge_style))
        elems.append(Paragraph(
            f"<b>Check ID:</b> {finding.check_id}  |  <b>Affected:</b> {finding.affected_url}",
            ParagraphStyle("meta", parent=styles["Normal"], fontSize=8, textColor=colors.grey),
        ))
        if finding.description:
            elems.append(Paragraph(f"<b>Description:</b> {finding.description}", styles["Normal"]))
        if finding.evidence:
            ev_data = [["Label", "Value"]] + [
                [e.label, e.value[:100] + ("…" if len(e.value) > 100 else "")]
                for e in finding.evidence
            ]
            ev_tbl = Table(ev_data, hAlign="LEFT", colWidths=[4 * cm, 11 * cm])
            ev_tbl.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID",       (0, 0), (-1, -1), 0.3, colors.grey),
                ("FONTSIZE",   (0, 0), (-1, -1), 8),
            ]))
            elems.append(ev_tbl)
        if finding.remediation:
            elems.append(Paragraph(f"<b>Remediation:</b> {finding.remediation}", styles["Normal"]))
        if finding.cwe:
            elems.append(Paragraph(f"<b>CWE:</b> {finding.cwe}", styles["Normal"]))
        if finding.framework_refs:
            refs_str = " | ".join(f"{k}: {v}" for k, v in finding.framework_refs.items())
            elems.append(Paragraph(f"<b>Framework refs:</b> {refs_str}", styles["Normal"]))
        if finding.references:
            elems.append(Paragraph(
                f"<b>References:</b> {' | '.join(finding.references[:3])}",
                styles["Normal"],
            ))
        elems.append(Spacer(1, 0.4 * cm))
        return elems

    def _appendix(self, result: ScanResult, styles) -> list[Any]:
        elems: list[Any] = [Paragraph("Appendix — Scan Metadata", styles["Heading1"])]
        meta = [
            ["Scan ID",      result.scan_id],
            ["Target",       result.target_url],
            ["Type",         result.scan_type.value],
            ["Started",      str(result.started_at)],
            ["Finished",     str(result.finished_at)],
            ["Risk Score",   str(result.risk_score)],
            ["Total Findings", str(len(result.findings))],
            ["Errors",       str(len(result.errors))],
        ]
        tbl = Table(meta, hAlign="LEFT", colWidths=[4 * cm, 11 * cm])
        tbl.setStyle(TableStyle([
            ("GRID",     (0, 0), (-1, -1), 0.3, colors.grey),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f5f5f5")]),
        ]))
        elems.append(tbl)
        if result.errors:
            elems.append(Spacer(1, 0.3 * cm))
            elems.append(Paragraph("<b>Scan errors:</b>", styles["Normal"]))
            for err in result.errors:
                elems.append(Paragraph(f"• {err}", styles["Normal"]))
        return elems
